apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app
  namespace: test-app
  labels:
    app: test-app
spec:
  storageClassName: SC
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: STORAGE # kpt-set: ${storage}
