apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test-app
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  type: ClusterIP
  ports:
  - name: test-app
    protocol: TCP
    port: PORT
    targetPort: TARGET
